### ISSUE TITLE
Not possible to depend on additional packages with sky_server

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/mojo#176]
Not possible to depend on additional packages with sky_server

sky_server overrides /packages, so if you want to have additional pub packages you have to symlink them into the gen/dart-gen folder.

This is just one more reason why we should ditch our current sky_server setup.

@johnmccutchan

**Comment by johnmccutchan** [comment]
I have a TODO on my desk about this issue. A couple ideas:

1) We could extend sky server so that it can scans multiple packages/ directories for a given url. In this scenario, the source tree provided packages (mojo, sky, etc) would be given priority and then we would fallback on the packages/ folder next to the program's entry point (i.e. main.dart / main.sky)

2) External packages that are used in tree are provisioned into a third-party directory and then linked into out/.../gen/dart-pkg/packages structure. This is what we do in the Dart SDK. It has a limitation though, only one version of a package can exist in the source tree, so all consumers must agree on that.

Long term:

Once package spec is supported throughout the Dart ecosystem, we can teach sky_server about it and then each package can be served up from whatever directory the developer has configured in their '.packages' file.

**Comment by sethladd** [comment]
Web development with Dart uses `pub serve`, its own dev-time web server. It's nice that it has something out of the box, but our experience shows that it also introduces complications. Before we decide to build a customer dev-HTTP server for Sky development...

One of the issues we encountered: many developers use frameworks/engines on their server that are not available to Dart. For example, it's common to use App Engine to host and serve your app, due to authentication APIs or it's a legacy requirement.

If App Engine is required, that means the developer will need to put the App Engine dev HTTP server in front of the Sky dev HTTP server, and intelligently proxy the requests from one to the other.

HTTP servers are responsible for a lot of concerns these days, and if we force a specific dev HTTP server implementation on developers, it greatly increases the complexity of setups and integrations.

If it's possible, I'd love for us to look at options where _any_ HTTP server can be used during development. Maybe we ship a small HTTP server out of the box, but in no way should it be required.

I think it's fine if our out-of-the-box dev HTTP server is the easiest way to do it, but we should make the BYOHTTPServer use case easy, too.

**Comment by johnmccutchan** [comment]
I just landed a [cl](https://chromium.googlesource.com/external/mojo/+/93cf2efbbe49d3134f2ec44a572e020963fc0fab) that brings in vector_math and box2d as external packages. If Sky needs other packages it should be easy to follow the pattern I laid out.

**Comment by ppiet** [comment]
Should this be moved to sky_engine issue tracker, or is obsolete now?

**Comment by johnmccutchan** [comment]
I believe this is obsolete now.
