### ISSUE TITLE
sky application layout

### ISSUE THREAD

**Issue by keertip** [domokit/mojo#273]
There is a convention for the layout of a dart application/package, documented [here] (https://www.dartlang.org/tools/pub/package-layout.html). It would be good if sky followed the convention and made it clear where the dart file with the entry point should be - either in the `web` or `bin` folder.

**Comment by abarth** [comment]
For now, we'd like to standardize on lib/main.dart as the entry point for a Sky application.  We don't want to use `web` because we're not using HTML and CSS.  We don't want to use `bin` because that integrates with `pub run`.

It's likely we'll want to revise our thinking after we implement our packaging format and/or our build tools for creating APKs and DMGs.

**Comment by abarth** [comment]
The convention that we've settled on is that the main entry point is in "lib/main.dart" in source form.  In production, there's a skyx file (which is basically just a zip file) and the main entry point is a script snapshot in the root called snapshot_blob.bin.

If there are things we can improve about this convention, please open a new bug explaining what can be improved and how.
