### ISSUE TITLE
Parser should block when waiting for <import> elements

### ISSUE THREAD

**Issue by esprehn** [domokit/mojo#35]
If you write 

```
<import src="app-panel.sky" />
<app-panel />
```

and the parser doesn't block, then the parser will produce an ```<error />``` element in sky, instead we should yield from the parser whenever we encounter a non-```<import>``` and then not resume until all the imports for the current module have loaded.

@Hixie @abarth @ojanvafai @eseidel

**Comment by Hixie** [comment]
The parser can tokenise, but yeah, it shouldn't actually modify the DOM until scripts are done. This is true even if we don't have the ``<error>`` behaviour, since you have to call the element constructors synchronously when adding the element, fire "end tag parsed" notifications, etc, and you can't do any of that until you've loaded your dependencies.

But it doesn't have to yield on any non-import element. Only unknown elements, unless I'm missing something.

**Comment by Hixie** [comment]
(The spec already says this BTW.)

**Comment by abarth** [comment]
Done.
