### ISSUE TITLE
Remove "all or none" support from two-phase data pipe APIs

### ISSUE THREAD

**Issue by yzshen** [domokit/mojo#366]
Symptom:  The websocket (backed by a data pipe) used by Manodline Telemetry testing consistently fails after ~1MB of data was sent.

Cause:
(1) Imagine the current circular buffer is: [0 - 99: free ] [100 - 109: occupied] [110 - 149: free]
(2) The user asks for a two phrase write. Minimal bytes to write is 50.
(3) The circular buffer thinks that the max size it can provide is 149 - 110 + 1 = 40, so it fails the call.
(4) Even if the user waits until all data in the circular buffer is drained, he still cannot request 50 bytes, because the start_index is set to 110.

Solution:
We need more sophisticated circular buffer management:
- We could skip [110 - 149] and return [0 - 49] for the user. (And keep record about the fragmented space.)
- On the other hand, if the user requests 110 bytes instead of 50, we will have to defragment by moving the occupied range to the beginning of the buffer.

/cc @viettrungluu-cr @jabdelmalek

**Comment by viettrungluu-cr** [comment]
The current behaviour is pretty much as designed. If you use two-phase
writes, you should know what you're doing.

**Comment by yzshen** [comment]
The issue is, for "framed" data (which has a minimal size requirement), the user doesn't have a good way to skip the remaining space at the end.

**Comment by viettrungluu-cr** [comment]
There's no guarantee of atomicity at all, so users must simply be willing
to split their writes.

**Comment by yzshen** [comment]
One thing that seems a little surprising is that: waiting until the pipe is drained doesn't help, because the start_index is not reset to 0. So it seems we shouldn't use MOJO_WRITE_DATA_FLAG_ALL_OR_NONE with two-phase write at all. Because when approaching the end of the buffer, it is likely that the call will never be satisfied again. (Similarly, two phase read shouldn't use ALL_OR_NONE, either.)

If that is expected behavior, maybe we should document it clearly, or even disallow this flag with two phase read/write? It doesn't show up if not enough data is passed, and it took me a while to realize the reason. Seems nice to help others to avoid it.

What do you think?

**Comment by viettrungluu-cr** [comment]
To be a little more specific, here are some things we do NOT guarantee:

   - We do not guarantee that you'll ever be able to do a two-phase write
   (or read) of any size at all (except for guarantees implied by element
   size). E.g., if we have some sort of communications channel which it's
   natural to limit read/write sizes, we may do so. (E.g., if we send data via
   messages with a maximum payload of 10 bytes, the two-phase write API may
   limit you to 10 bytes. Or if we use a shared memory buffer not for the
   entire ring buffer but for individual transfers, we may limit you to that
   buffer's size.
   - We do not guarantee that just because someone wrote N bytes (using any
   API), that all N bytes will show up on the receiving end all at once.

**Comment by viettrungluu-cr** [comment]
Disallowing "all or none" for the two-phase APIs seems reasonable to me.

**Comment by yzshen** [comment]
Thanks Trung.
