### ISSUE TITLE
Change IntentReceiver from a Service to a non-UI activity

### ISSUE THREAD

**Issue by emembrives** [domokit/mojo#368]
`IntentReceiver` is currently a Service. However, it is only possible to receive intents on Activities, so all potentially active activities have code (`onActivityResult`) to forward intents to the receiver.

This fails in the New World because there is no guarantee any particular activity would be up at any time, nor it is correct to start a UI activity outside of the normal workflow. Thus, we need to change `IntentReceiver` into a non-UI activity so it can receive intents itself.

**Comment by j9brown** [comment]
I don't think this is the right way to intermingle the lifecycle concerns.
onActivityResult gets called specifically when returning from some other
activity that was started by startActivityForResult.  It's got to have
somewhere to go!  The expectation is that we are returning to the caller's
UI.

Jeff.

**Comment by emembrives** [comment]
I am not sure to understand your point. This bug is precisely to make sure the caller (in that case, soon-to-be-renamed `IntentReceiverService`, receives the result directly and not through an indirection through a different activity that had nothing to do with calling startActivityForResult.

If you say that `startActivityForResult` should only be called by the current UI activity, then I guess we have a much bigger problem. `startActivityForResult` is currently used by the authentication system to ask for OAuth tokens. There is absolutely no guarantee a UI would be running at the time of the request (this could be the first request). And, within mojo, we try to maintain a separation of concerns which is lacking on Android. In particular, I don't see why we should tie network authentication, or nfc, to UI management.

**Comment by emembrives** [comment]
@gauthamt this refers to your problem

**Comment by j9brown** [comment]
So what I am saying is basically that we're doing it wrong.  The
authentication is intentionally tied to the currently running activity
because it might need to show some UI and we don't want dialogs popping up
randomly with no obvious link to their cause.

The idea is that the user is in an app, does something that needs auth, the
app starts the auth activity, auth gets pushed on the stack, auth does its
thing, then returns a result back to the app.  startActivityForResult() is
like a UI based subroutine call.

Android has deliberately tied these things together so that the user has
some context for the prompt which is about to appear.  It's similar for
optional permissions too and many other APIs.

For Mojo too we will have to give some thought to how we empower and inform
the user through interactions of this sort.  Stuff needs some kind of
context.  The fact we aren't doing that in Mojo is a bug.  :)

(FWIW, the bytesToIntent function is problematic.  Intents are not intended
to be serialized like that since they may contain binder objects.)
Jeff.
