### ISSUE TITLE
network_fetcher loses chunks of file when running with --enable-multiprocess

### ISSUE THREAD

**Issue by nlacasse** [domokit/mojo#373]
When running a mojo app with "--enable-multiprocess" flag, the network_fetcher downloads and caches files, but the cached files are smaller than the original files being served.

The cached files are always smaller than the original by a multiple of 64k bytes.

Steps to reproduce:

1. Edit `examples/echo/echo_client.cc` and replace `"mojo:echo_server"` with `"https://core.mojoapps.io/echo_server.mojo"` on line 29.

2. Rebuild: 
`./mojo/tools/mojob.py gn && ./mojo/tools/mojob.py build`

3. Run the echo client:
`./mojo/devtools/common/mojo_run --enable-multiprocess "mojo:echo_client"`

The app will crash, usually with an error about "invalid ELF header".

If you compare the original file with the cached file, you see that the cached file is smaller than the original by a multiple of 64k bytes.

```
$ ls -l out/Debug/echo_server.mojo 
-rwxrwxrwx 3 nlacasse eng 27347840 Aug 11 17:44 out/Debug/echo_server.mojo

$ ls -l /usr/local/google/home/nlacasse/.mojo_url_response_disk_cache/http_3a//127.0.0.1_3a34168/echo_5fserver.mojo/.org.chromium.Chromium.HULbBc
-rw------- 1 nlacasse eng 27216768 Aug 11 18:10 /usr/local/google/home/nlacasse/.mojo_url_response_disk_cache/http_3a//127.0.0.1_3a34168/echo_5fserver.mojo/.org.chromium.Chromium.HULbBc
```

**Comment by nlacasse** [comment]
cc @viettrungluu-cr @asadovsky @bprosnitz

**Comment by viettrungluu-cr** [comment]
Notes:
* It's actually not always necessarily 64 KB.
* There are definitely bytes missing at the beginning of the file.
* common::CopyToFile() writes out everything it gets (or thinks it gets) from the data pipe.

**Comment by viettrungluu-cr** [comment]
Moar notes:
* (The mojo::common::CopyToFile() alluded to previously was in url_response_disk_cache_impl.cc.)
* But even if instead of delegating (via GetFile() to the disk cache, we simply do a CopyToFile() directly in the network fetcher (hence in the shell), in particular in NetworkFetcher::AsPath(), we still have the same problem.
* So it seems not unlikely that the problem could be in the network service itself.

**Comment by viettrungluu-cr** [comment]
Problem seems to be in the system layer somewhere.

**Comment by viettrungluu-cr** [comment]
Notes to self:
* The problem is between `RemoteProducerDataPipeImpl::ConsumerEndSerialize()`, which calls `owner()->SetProducerClosedNoLock()` (in the producer open case), and `RemoteProducerDataPipeImpl::OnReadMessage()`, which eats the message if the producer is closed.
* The latter part is obviously wrong/suspicious -- if you know the producer is closed, you wouldn't (normally) be receiving a message from it (unless the other process is misbehaving).
* To compare, `MessagePipe::OnReadMessage()` returns false in the analogous case, with a comment about a race condition (probably exactly the same type as we're encountering here).
* Unfortunately, just returning false in `RemoteProducerDataPipeImpl::OnReadMessage()` makes stuff blow up elsewhere ... so I guess I should actually try to understand this.
