### ISSUE TITLE
Dart content handler: Time between remote function calls is too high

### ISSUE THREAD

**Issue by qsr** [domokit/mojo#430]
I added a benchmark that trace an event in the initialize method of application, and in the acceptConnection methods for both C++ and Dart.

When running this on Linux, the time between the 2 C++ events is ~ 0.2 ms.
In Linux, for dart, the time between 2 events is ~30 ms.

You can reproduce this by running:
./mojo/devtools/common/mojo_benchmark mojo/tools/data/benchmarks

**Comment by tonygentilcore** [comment]
That's really interesting. If I'm reading it right, it suggests that the minimum time for an IPC in Dart is ~30ms on linux? Wonder if there's some low hanging fruit in the bindings there and whether we should have a benchmark that just measures IPC round trips in Dart. I guess it's also possible that things get significantly faster after the first few happen and then we start running opt code.

/cc @iposva-google @zanderso

**Comment by zanderso** [comment]
Calls to waitForMilliseconds() block the thread and make it impossible for the app to respond to any messages.

**Comment by j9brown** [comment]
We need this number to be down in the tens of microseconds range.  Although
I expect there is more low-hanging fruit to be found, be sure to check the
timer slack.

**Comment by zanderso** [comment]
Just to clarify, the Dart numbers probably won't mean very much until the calls to waitForMilliseconds() are removed from the benchmark.

**Comment by zanderso** [comment]
Commented here as well https://github.com/domokit/devtools/issues/45#issuecomment-141150952 that that call is leaking handles.

**Comment by jamesr** [comment]
@zanderso the time to the initialize() call shouldn't be impacted by the waitForMillisecond() calls or leaked handles, however, as that trace should be hit before any of the other code mentioned runs.  This would be a clearer benchmark of startup if it simply initialized, traced, then shut down.

**Comment by emembrives** [comment]
@zanderso: After fixing #471, I looked into why I still didn't see any improvement in the `mojo/tools/data/benchmarks`, and why there is such a difference with `mojo/tools/data/rtt_benchmarks`.

It turns out that `mojo/tools/data/benchmarks` is measuring the time it takes to send the first messages to  application "endpoints", (acceptConnection, or the first call on a service method), whereas `mojo/tools/data/rtt_benchmarks` measure the round-trip time when all code paths have already been exercised repeatedly (there is 5 seconds of "warmup" messages, with one message every 50us). Once I modified the `Dart <=> Dart` test to check the round-trip time of the first message[1], I got back the same timing as seen in the first benchmark, ~40 ms for Dart to Dart and ~20ms for Dart to C++ in Linux, ~140ms and ~70ms on Android respectively. I looked at the traces, but I don't see any event, including from Dart VM and Dart content handler, during these pauses.

We are currently trying to improve warm start of Mojo applications, and this is a high cost to pay each time we call an uncalled-before method. I suppose these pauses corresponds to dart code being compiled. If that's the case, would it be possible to store the compiled bytecode on disk and load it there on warm starts? This way, we would pay this cost only on cold starts, which is much less painful.

[1]: the modified test connects to the echo server, waits 5 seconds, then sends a unique ping.

**Comment by zanderso** [comment]
Yes, long pauses like this at startup are currently expected due to compilation. We have several folks already working on precompilation and background compilation, so those efforts are well underway. The rtt_benchmarks are not measuring startup, but rather steady-state performance so that we can track and make improvements there as well. Also, note that the 5 second warm-up in the benchmark is very conservative---the real warm-up time likely to be very much shorter.

**Comment by zanderso** [comment]
Lots of work has gone into performance since last year, and there have been no complaints about messaging performance in the meantime. I'm going to close this one, and encourage folks to file new issues if specific performance problems arise from here on out.
