### ISSUE TITLE
skydb takes ~30 seconds to start now that we pass in the --origin flag

### ISSUE THREAD

**Issue by ojanvafai** [domokit/mojo#45]
It takes < 3 seconds without --origin.

@eseidel

**Comment by eseidel** [comment]
I suspect we'll get most of this back by turning on the http disk cache on linux too.  @esprehn  (correctly) made the http cache memory-only on linux to fix parallel mojo_shell instances for testing.  @abarth turned the http disk cache back on for android to fix some of this slownesss, but we need to turn it on for linux too and dynamically turn it off when using parallel mojo_shells in testing mode.

I suspect a lot of the slowness is sky_server having to send these multi-hundred megabyte .so's across sky_server to mojo_shell every time and then mojo_shell copying them on disk at least once.  I'm sure we could (and should) optimize some of that since in the wild mojo_shell has to at least pull the binaries from the network.  The the binaries are of course much smaller in Release than Debug.  @aboodman

**Comment by abarth** [comment]
skydb has been replaced by mojo_shell.py.
