### ISSUE TITLE
Dart unclosed handle checking should be done inside Dart (possibly using a Zone)

### ISSUE THREAD

**Issue by jamesr** [domokit/mojo#478]
The dart embedding C++ glue code here:

https://github.com/domokit/mojo/blob/master/mojo/dart/embedder/mojo_natives.cc#L154

keeps a set of unclosed Mojo handles in a state object attached to the Dart isolate and performs actions on it when an unhandled dart exception occurs:

https://github.com/domokit/mojo/blob/master/mojo/dart/embedder/dart_controller.cc#L454

This means that any code using this C++ glue code has to agree with it on the shape of the object in the Dart isolate's one storage spot.  Concretely, this means the code isn't reusable in Flutter even though it wants to do exactly the same thing but also needs to store its own data in the Dart isolate storage space.

The handle checking logic should be implemented in Dart instead and use a Zone (https://www.dartlang.org/articles/zones/) to register handles from the Dart side and handle uncaught exceptions.  This would make the C++ code reusable.

**Comment by zanderso** [comment]
I think doing this in Dart would be a little tricky. I think we'd have to wrap main() in a function to set up the zone in builtin.dart. We'd also have to make sure that Isoate.spawn() and Isolate.spawnUri go through the same or a similar wrapper. The error handler for the zone would close remaining open handles.
Two potential issues:
1. Errors can't cross Zone boundaries, so it's not immediately clear to me how the unhandled exception would be reported to the embedder.
2. We would no longer have the option of using RawReceivePorts anywhere in Mojo or Flutter code since they do not respect Zones. It would be nice to leave this option available for performance improvements to isolate communication, which is currently used between the handle watcher isolate and application isolates, if needed.

**Comment by abarth** [comment]
I was imagining that `main` would call something in the Dart Application framework to set up the zoning properly.  All the tracking of opened handles would happen inside Dart and the C++ code wouldn't be involved at all.

**Comment by jamesr** [comment]
What do you mean by 'RawReceivePorts do not respect zones'?  Do you mean if you register a callback on a RawReceivePort and that callback generates an exception the exception wouldn't be caught by the zone's error handle?

**Comment by zanderso** [comment]
@abarth: I see. How would we ensure that this function is called in main, and in all functions passed to Isolate.spawn()? Code review?
@jamesr: That's correct. Exceptions from RawReceivePort handlers go to the root Zone.

**Comment by jamesr** [comment]
The Dart application framework could expose the Mojo entry points only within its Zone, then any Dart code running outside the Zone (for whatever reason) could do whatever it liked but not manipulate handles.

**Comment by abarth** [comment]
@zanderso How unclosed handles are treated would be an opinion of the Dart application framework.  There's no requirement to use the Dart application framework, just as there's no requirement to use ApplicationImpl in C++.  However, if you do use the Dart application framework, it could assert or otherwise get mad if it wasn't run in the proper zone.

**Comment by zanderso** [comment]
Got it. I will take a stab at this. In checked mode, we already do some tracking of unclosed handles that also collects stack traces when MojoHandle objects are created. First, I'll add Dart tracking that directly replaces what we do in C++, and then I'll see if there's a way to merge with the existing checked mode tracking.

**Comment by zanderso** [comment]
After consulting with @iposva-google, I learned that it's possible to call back into Dart code from the unhandled exception callback provided by the embedder. This way, we can do the tracking in Dart code without using a Zone: https://codereview.chromium.org/1411843005/.
