### ISSUE TITLE
reportLeakedHandles() in Dart only seem to work in strict mode

### ISSUE THREAD

**Issue by aghassemi** [domokit/mojo#482]
`MojoHandle.reportLeakedHandles()` does not seem to report anything when Dart content handler is not in strict mode. Simply adding `?strict=true` to the content handler for the test runner causes `MojoHandle.reportLeakedHandles()` to start reporting leaks when called.

**Comment by tonygentilcore** [comment]
I pretty sure that's WAI. Can you explain more about why this is a problem? Is it just that we're not running some test in checked mode that we should be?

/cc @johnmccutchan

**Comment by aghassemi** [comment]
Not an actual problem maybe, but I guess I just did not make the connection between `reportLeakedHandles()` and `strict` mode initially and wrongly assumed we were checking for leaks by calling `reportLeakedHandles()` and later discovered that was not the case.

If it is not an overhead to always track handles, it would be nice if `reportLeakedHandles` always reports them regardless of the mode. If not, maybe when `reportLeakedHandles` is called in non-strict mode, it can fail with a message ( at least somehow print a warning ) indicating the behavior.

**Comment by johnmccutchan** [comment]
@aghassemi It's actually the assert that reportLeakedHandles is wrapped in that is causing your issue.

If you have Dart code like the following:

assert( expr );

expr is only evaluated in strict mode.

As @tonygentilcore said this is WAI. If you want it unconditionally- just don't wrap it in an assert.

**Comment by aghassemi** [comment]
@johnmccutchan In our case, there is no assert, we are using it in testing and we do a `expect(MojoHandle.reportLeakedHandles(), isTrue);`, The expectation seem to pass when tests are running in non-strict mode but fails in strict mode. If `reportLeakedHandles()` is expected to work in non-strict mode, there could be something else happening that is causing what I see. I will look into it a bit more.

Thanks

**Comment by zanderso** [comment]
In tracking leaked handles, we record a stack trace when a MojoHandle is allocated. That's pretty expensive so we only do it when strict=true. The library code to add and remove handles from the leak tracking, which records the stack traces, is therefore wrapped in assert()s so that it only runs when strict=true. So, calling reportLeakedHandles without strict=true will always pass and report no leaked handles since the code to track handles is disabled.

To get reportLeakedHandles to fail when strict=false, we'd have to think up a bit of Dart code that would succeed when we're doing *more* checking, but fail when we're doing *less* checking. This is possible, but I wonder if we should instead solve this problem by thinking of a better name instead of 'reportLeakedHandles'?

**Comment by aghassemi** [comment]
I think it would be reasonable for `reportLeakedHandles` to throw an exception when called in non-strict mode.

**Comment by johnmccutchan** [comment]
We will soon be unconditionally tracking unclosed handles in package:mojo, we should just make reportLeakedHandles work all the time and only have a stack trace associated with a handle in strict mode.
