### ISSUE TITLE
Managing Arguments to Mojo apps

### ISSUE THREAD

**Issue by afandria** [domokit/mojo#489]
My Mojo apps rely on arguments, but I am beginning to think that I am not managing them the "Mojo" way.

(Related: #488; my way leads to overly long adb commands)

Currently, my apps have a heavy reliance on `--args-for`, but that means that these arguments can only be specified when starting up the Mojo shell. They cannot be specified upon connecting to my Mojo app (i.e., programmatically). Thinking of Android apps in particular, I foresee serious problems with my current setup. For example, I want to build a standalone app and also have the arguments passed in vary depending on my program's state, but as-is, it does not look like that will be possible.

Instead of `--args-for`, each Mojo app could include an Init function that takes in the arguments. Does Mojo expect applications to send arguments this way?

**Comment by jamesr** [comment]
Mojo generally expects configuration will come from other Mojo apps.  `--args-for` is a way to send data in from the outside.

It's possible to send parameters when connecting to a Mojo app by sneaking them into query parameters of the connection URL and then parsing them out of the URL when the connection is initiated, but that has similar length and sanity issues.  For more detailed programmatic configuration it's probably a good idea to write a service that exposes the configuration information in a structured way and have the connecting app pass configuration information through this interface.  This lets you use mojom types for configuration instead of trying to hide everything in a string.

**Comment by afandria** [comment]
Thanks, that answers my question. I didn't know about the URL trick, but I think I'll opt for the other two methods of sending in args/configs.
