### ISSUE TITLE
Remove mojo/common/dart/lib/tracing_helper.dart and use dart:developer's Timeline

### ISSUE THREAD

**Issue by johnmccutchan** [domokit/mojo#546]
tracing_helper is no longer needed because Dart officially supports tracing via Timeline.

Also, tracing_helper doesn't use the correct thread (it just makes up a random thread id) making the traces much less useful when combined with the VM's native traces.

**Comment by johnmccutchan** [comment]
@zanderso @MitchRudominer @qsr

**Comment by johnmccutchan** [comment]
Blocks #545

**Comment by zanderso** [comment]
For

https://github.com/domokit/mojo/blob/master/benchmarks/mojo_rtt_benchmark/lib/main.dart

we do kind of a hack to reduce the tracing overhead. (We're trying to measure on the order of tens of microseconds for this benchmark so this turns out to be significant.) In particular, tracing_helper let's us send a Duration event directly instead of sending a Start and an End event separately. Would it be possible to add an interface like that to Timeline?

**Comment by zanderso** [comment]
If it doesn't already have one, that is.

**Comment by johnmccutchan** [comment]
@zanderso I'm confused- Timeline emits Duration events and not Begin and End events separately.

**Comment by zanderso** [comment]
Okay, cool. Then we should be able to use it in the RTT benchmark. I'll try switching it over.
