### ISSUE TITLE
mojom: Structs with nullable unions are transferred incorrectly.

### ISSUE THREAD

**Issue by j9brown** [domokit/mojo#572]
The C++ bindings seem to be incorrect for structs containing nullable unions.  In particular, the union effectively becomes non-nullable.

```c++
struct S {
  U? u;
  X? x;
};

union U {
   int32 value;
};

struct X {
    int32 value;
};
```

We can see the difference in the serialization by looking at the generated S_Data structure, which will look something like this:

```c++
class S_Data {
  // ...
  internal::U_Data u;
  mojo::internal::StructPointer<mojo::internal::X_Data> x;
};
```

Notice how the U union member's data was pulled inline whereas the X struct member's data is indirected through a StructPointer.  This is actually a nice property, however...

If I pass an S across a message pipe with a null |u| field, on the other side it comes across as a non-null |u| field containing a default-initialized U with an invalid tag!

ie. s->u->has_unknown_tag() == true but we expected s->u == nullptr.

The expected behavior would be for a null |u| field sent into the message pipe to be materialized on the other size as a null |u| field, just the same.

**Comment by vardhan-cr** [comment]
This is definitely a bug.  I think the problem is that a UnionPtr is always initialized (i.e., and therefore not null) regardless of it is null.  I'll work on a patch for this, thanks for reporting!

BTW:
- s->u should not be nullptr, but it should be s->u.is_null().  (assuming |u| is SPtr, not U_Data)
- I think the S_Data declaration you see there is as intended -- nullable/null unions are inlined when they are in structs, because they are only ever 16 bytes (32-bit size + 32-bit tag size + union data, which i believe in practice will only ever be 64-bits).  note that unions within unions are encoded as UnionPointer though, i.e. not inlined

**Comment by j9brown** [comment]
Oh that's weird.  For the record, I hate is_null() for arrays and strings
and think it should die.
