### ISSUE TITLE
Mojom Compiler: Field names should not be allowed to be equal to value names.

### ISSUE THREAD

**Issue by MitchRudominer** [domokit/mojo#620]
Consider the following Mojom:
```
const int32 foo = 42;
struct MyStruct {
  string foo = "hello";
  int32 bar = foo;
};
```
The Mojom parser allows this but the generated C++ code fails to compile because the reference to `foo` in `int32 bar = foo` is taken to be the string member foo instead of the constant foo.

Even worse, consider 
```
const int32 foo = 42;
struct MyStruct {
  int32 foo = 43;
  int32 bar = foo;
};
```
This generates code that does compile but the default value of `bar` is 43 instead of 42.

**Comment by viettrungluu-cr** [comment]
Hmmm, this is weird.

What's our general resolution algorithm? If it's C++-like, then the "foo" in "foo = bar" resolving as it does is "correct". The parser should generate errors in both cases, but because you shouldn't be able to assign to value names.

But do we allow syntax like `bar = .foo` (to indicate the "root" module, like `::foo` in C++)?

**Comment by MitchRudominer** [comment]
In answer to your first question, the Mojom parser does not support references to fields at all. So the following is not accepted:
```
struct MyStruct {
  int32 foo = 43;
  int32 bar = foo;
};
```
The problem with the previous snippet is that the parser allows it because as far as the parser is concerned `foo` does not refer to a field but then it generates code for which the C++ compiler thinks it does.

Regarding your second question: No, `bar = .foo` will not be accepted because the parser believes that identifiers have to begin with a name.

**Comment by MitchRudominer** [comment]
To be clear, my proposal is that the parser should reject the two snippets at the top of this bug, complaining that the name of the filed `foo` leads to ambiguity.

**Comment by viettrungluu-cr** [comment]
Oops, wrong button.

I wonder if we should do name lookups uniformly. I.e., in "bar = foo", it'd always pick up "foo" as being the "foo" *in* the struct, but then reject it since it's the wrong type (i.e., it's a value, not a constant).

I also wonder if we shouldn't have some syntax for escaping to the global namespace/module. Otherwise, I guess all names should be fully qualified (i.e., from the root/global namespace module).

**Comment by MitchRudominer** [comment]
Regarding your second point: Yes, I agree. We should have some syntax for specifying that a reference should be interpreted relative to the global scope.

Regarding your first point: The resolution algorithm does in fact look in the local scope before looking elsewhere. But in the examples given above the name of the field foo is never registered in any scope because it is not a referent. That is,  it is not something that can be referred to so there was no reason to register its name in any scope. 

Maybe the way to implement the fix (and maybe this is exactly what you are suggesting) is that the name of the field foo should be registered in the local scope even though it is not a referent. Then at resolution time if there is a reference to "foo" we would find the name in the scope and issue an error that the name refers to a non-referrent.

**Comment by viettrungluu-cr** [comment]
I think that's a good solution. Note that while there's no reason to refer
to field names in mojom files themselves, there may be uses in other
contexts (e.g., in a debugger, maybe one would want to be able to look up
"MyStruct.foo", to learn that it's a field of a certain type). (I'm not
sure if this observation has any bearing on the implementation of the fix.)
