### ISSUE TITLE
Mojom Structs are no longer allowed to have fields whose type matches their value.

### ISSUE THREAD

**Issue by afandria** [domokit/mojo#648]
Related #620 and https://github.com/domokit/mojo/commit/9933616fe39c4de7bdd081aef9d7f40e440e314e

I wanted to confirm that this new behavior is intended. I think there is likely to be a bug somewhere though due to an inconsistency with how this rule applies to structs and unions.

====================

The following used to compile:

```
enum TestEnum {
  A, B, C
};

struct TestBasicStruct {
  TestEnum TestEnum;
  int32 a;
}
```

But now receives an error along the lines of...

```
mojom/mojom/tests/transcoder_testcases.mojom:47:3: Error: "TestEnum" does not refer to a type. It refers to the field v23proxy.tests.transcoder_testcases.TestBasicStruct.TestEnum at /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/mojo/v23proxy/mojom/mojom/tests/transcoder_testcases.mojom:47:12.
  TestEnum TestEnum;
  ^^^^^^^^
```

To confirm this, I modified `//mojo/public/interfaces/bindings/tests/test_unions.mojom`. This also doesn't compile (similar error about `ObjectUnion`).

```
struct StructOfUnions {
  ObjectUnion ObjectUnion; // Used to be "u;"
  array<ObjectUnion> a_ou;
  array<HandleUnion> a_hu;
  map<int64, ObjectUnion> m_ou;
  map<int64, HandleUnion> m_hu;
};
```

Interestingly, union types (unlike structs) are allowed to have the name of the field's type match the name of the field's value. The following does compile (`AnEnum` is both the field type and name):

```
union PodUnion {
  int8   f_int8;
  int8   f_int8_other;
  uint8  f_uint8;
  int16  f_int16;
  uint16 f_uint16;
  int32  f_int32;
  uint32 f_uint32;
  int64  f_int64;
  uint64 f_uint64;
  float  f_float;
  double f_double;
  bool   f_bool;
  AnEnum AnEnum; // Used to be "f_enum;"
};
```

@MitchRudominer

**Comment by MitchRudominer** [comment]
I'll look into this.

**Comment by afandria** [comment]
Thanks, FYI. I've also discovered that this also applies to Interface Methods. Their arguments can't have types whose name is the same as the method name.

```
mojom/vanadium/discovery.mojom:85:10: Error: "Update" does not refer to a type. It refers to the method discovery.ScanHandler.Update at /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/mojo/discovery/mojom/vanadium/discovery.mojom:85:3.
  Update(Update update);
```

**Comment by MitchRudominer** [comment]
Here are a few findings:

(1) The old Mojom compiler did permit these types of duplicate names. But the generated C++ code fails to compile.

(2) The new Mojom compiler did permit these types of duplicate names prior to
https://github.com/domokit/mojo/commit/9933616fe39c4de7bdd081aef9d7f40e440e314e
but it also produced C++ code that fails to compile.

(3) The new mojom compiler after the above-mentioned commit prohibits these types of duplicate names. There is a discussion about the topic in https://github.com/domokit/mojo/issues/620.

(4) Most of these types of duplicate names are forbidden in the analogous situation in C++. That is, in C++ a struct field may not have the same name as its type. However the last example that you mentioned is allowed in C++. A function may have the same name as the type of its parameter. This is because the rules for name-lookup in C++ are different for functions.

(5) The fact that the current version of the new compiler allows the duplicate name in the case of a union field is an oversight/bug. Interestingly the generated C++ code does seem to compile. I'm not sure why because in a simple hand-written C++ program that I tested a union field was not allowed to have the same name as its type.

(6) The philosophy introduced into the code in https://github.com/domokit/mojo/commit/9933616fe39c4de7bdd081aef9d7f40e440e314e
is to use a uniform name lookup in scopes. That is, regardless of the context, all names declared in a scope will be matched during a name lookup. This is admittedly restrictive but it seems like a good idea to me since we will be generating code in multiple languages each of which have their own name lookup procedures. Being very restrictive like this seems to me like it will minimize possible confusion with the generated code.

That said, I am open to counter-arguments. Can you give a good argument why these types of duplicate names should be allowed given the points I made above.

**Comment by afandria** [comment]
Nice investigation!

I agree about not allowing Struct field names match their type's name.

However, I do think it is a problem if we disallow a method name to match the name of its argument's type. I do like the idea of short and simple method names `Update(Update update);`. While it is strange for every argument's type to limit the number of available method names, it is not too difficult to simply pick a different or less convenient name. (We can't necessarily change the struct name since it might have come from someone else's mojom file.)

So the issues I can think of so far are:
* usability (extra gotchas to learn on top of the Mojom syntactic rules)
* method name's cannot always be short. (You may actually have to say `SetFoo(Foo foo);` instead of just `Foo(Foo foo);`.)

Overall, these issues aren't that bad for me. I'll think about this problem some more, but currently, I am not very troubled by this limitation.

**Comment by MitchRudominer** [comment]
Alex I am closing this bug. If you still have a feature request please open a new one with a more specific description. Thanks.
