### ISSUE TITLE
[Go bindings generator]:  Fix the StudlyCaps generated for enum value names

### ISSUE THREAD

**Issue by vardhan-cr** [domokit/mojo#708]
Enum values are stylized as StudlyCaps right now, which doesn't work very well with alphanumeric names;  ```INT8``` in mojom translates to ```InT8``` in the Go bindings.

Right now, this mojom enum (taken out of mojom_types.mojom):
```mojom
enum SimpleType {
  BOOL,
  INT8,
  INT16,
}
```

generates this for the go bindings:

```go
type SimpleType int32
const (
  SimpleType_Bool = 0
  SimpleType_InT8 = SimpleType_Bool + 1;
  SimpleType_InT16 = SimpleType_InT8 + 1;
)
```

```SimpleType_InT8``` is very odd looking.  Ideally, I think it should be ```SimpleType_INT8``` (i.e., preserve the value name styling), but this might involve tracking down a ton of consumers and fixing them, so maybe it should be fixed to ```SimpleType_Int8```

**Comment by vardhan-cr** [comment]
@zanderso @AlexandreZani @MitchRudominer

**Comment by zanderso** [comment]
I think the Dart generator might do the right thing here. Compare the regexps here: https://github.com/domokit/mojo/blob/master/mojo/public/tools/bindings/generators/mojom_dart_generator.py#L238 with the Go ones here: https://github.com/domokit/mojo/blob/master/mojo/public/tools/bindings/generators/mojom_go_generator.py#L113

IIRC, the issue is handling numbers in the names correctly.

**Comment by vardhan-cr** [comment]
Thanks for the pointer @zanderso!  I'll patch this.
BTW, I noticed that dart version's regexp tries to consume "1-9".  Any reason this isn't 0-9?

**Comment by zanderso** [comment]
Probably a typo.
